### ISSUE TITLE
test run is ok; suggestions for conda

### ISSUE THREAD

**Issue by danrlu** [AndersenLab/alignment-nf#5]
Results can be found here:
/projects/b1059/projects/Dan/alignment-nf

The only thing I noticed is that `conda "bwa=0.7.17 sambamba=0.7.0"` will create the environment on the fly and (1) is slow (2) will create a new environment every time the script runs (3) add all these unnamed environment to conda env list.

So it's probably better to take environment creation out of the pipeline. Can export the .yml from conda as a record for the environment. 

Otherwise all is good.

**Comment by danielecook** [comment]
I believe we are all set on this.
